### ISSUE TITLE
Gemini的api能采用轮询的方式访问吗

### ISSUE THREAD

**Issue by 9530045** [Xwudao/reman-release#1]
![image](https://github.com/user-attachments/assets/2fc3093c-30aa-404f-8a12-6e572499abe7)

免费套餐的Gemini，每天的调用额度只有1500次，以及每分钟不得超过15次，这两个限制对于入库数据比较多的用户，很容易超额。

但是如果可以将多个账号的api一起使用，采用轮询访问的使用，这可以将很大提高额度的限制。

以上也只是作为一位ReMan网盘的用户，对于使用Gemini的一些建议。

如果你也觉得不错的话，望请采纳，谢谢！

**Comment by Xwudao** [comment]
https://github.com/Xwudao/reman-release/releases/tag/v0.8.1
