### ISSUE TITLE
关于提交链接页面

### ISSUE THREAD

**Issue by 9530045** [Xwudao/reman-release#12]
近期发现一个问题，也不能算是问题吧，就是还能有优化的空间，就是提交链接窗口，能不能单独做成一个页面，就像是混合盘提交链接页面。如下图
![image](https://github.com/user-attachments/assets/38136728-25dc-4eb6-b846-5b8686e2a044)
因为从最近我的网站来看，还是很有必要的，因为随着用户越来越多，后台能处理的链接数量，基本是固定的，一般一天最多就能处理2万左右的链接。
有时候用户提交的资源会比较多，导致后台堆积了几万甚至几十万的链接，没来得及处理。总是会有用户来问，他提交的链接怎么不显示，我看了有些是被黑名单拦截，还有一大部分的没来及处理。
还有个别的用户重复提交资源，也是占用了很多处理资源。
如果能做成像混合盘的提交链接页面，右侧能显示一些提交规则，能实时查看后台的列队数量，还能查询自己提交的链接入库状态，这样能让提交的用户心里有点B数，不至于，提交了链接，但是不知道有没有收录，或者多久收录，也不知道链接是什么状态。
以上的话，也是我从最近网站的状态，提出的一点意见，还请作者考虑一下这个功能。

**Comment by Xwudao** [comment]
该版本可以限制每日用户提交的次数，也可设置黑名单用户

https://github.com/Xwudao/reman-release/releases/tag/v0.8.9

暂不考虑另设提交页面
