### ISSUE TITLE
关于API导入任务的审核的问题

### ISSUE THREAD

**Issue by ymp12345** [Xwudao/reman-release#14]
# 功能请求
## 导入资源API请求时可以自动通过审核
这两天发现有没素质的用户大量提交短剧资源，通过多个夸克账号提交重复资源，所以想打开审核功能，
但是自己写了点小爬虫，通过以下api导入，如果打开审核功能，此部分API链接无法及时被网站爬取，需要单独审核，
希望可以让API提交的资源不需要审核直接爬取，而用户提交的资源需要审核。
谢谢！

![image](https://github.com/user-attachments/assets/3a24f67c-cebc-4991-8523-a7b0babc09a3)

![image](https://github.com/user-attachments/assets/e4502204-f3c6-46f9-8842-fa5e3bb8ea2b)

## 关于数据库删除的行如何更新到网站
另外还有个问题想问下，由于上述用户的问题，我删除了部分数据库的行，但是前台仍然可以搜索到数据，点击该删除的数据后，会显示如下内容，请问我该如何处理，只有重建索引嘛，谢谢
![image](https://github.com/user-attachments/assets/b1e0f222-beeb-4ac5-90fd-456c29435e8c)

**Comment by Xwudao** [comment]
![image](https://github.com/user-attachments/assets/b8c31372-6492-4354-9f3d-5b06a2fac4d0)

你可以开启如上设置，至于“API提交的资源不需要审核直接爬取”，下个版本待定；

----

重建索引
