### ISSUE TITLE
【BUG】V0.89版本API无法提交资源

### ISSUE THREAD

**Issue by ymp12345** [Xwudao/reman-release#15]
# BUG 提交

## 错误描述

更新V0.89版本后，API无法提交导入任务，可以看下面的截图，昨晚更新后一直没有数据，今天替换到0.88版本后正常
![image](https://github.com/user-attachments/assets/5d34d576-787b-4424-aa00-e26b4aa2f557)

## 运行环境信息

- ReMan 版本：

[v0.8.9]

- 操作系统：

[Ubuntu 22.04 LTS]

**Comment by Xwudao** [comment]
https://github.com/Xwudao/reman-release/releases/tag/v0.8.10
