### ISSUE TITLE
【FEAT】增加两个页面

### ISSUE THREAD

**Issue by 9530045** [Xwudao/reman-release#18]
# 功能请求

## 希望增加“隐私政策”以及“注册协议”页面

因为最近在申请谷歌广告联盟，但是申请了两次都被拒了，我就在网上查询相关的失败案例，最后总结出一个问题，就是差了两个页面。
分别是“隐私政策”跟“注册协议”，原因也很简单，因为谷歌广告联盟的“欧盟GDPR”协议中有提到这一点。据说是去年就开始要求的。
所以在这里也是希望作者能添加上。

**Comment by Xwudao** [comment]
和网站质量有关系，有reman网站申请成功的...

有时候，并不是你们自以为的、所谓的”因“和”果“
