### ISSUE TITLE
【BUG】关于批量修改用户ID任务的状态

### ISSUE THREAD

**Issue by ymp12345** [Xwudao/reman-release#19]
# BUG 提交

## 描述该错误
我设置的默认用户提交的资源需要审核
假设用ID 29 第一次提交50个资源，我将审核状态改为pending，爬取完成Finnish。
ID 29 第二次提交20个资源，我再选择这个用户ID改成pending，会将已经爬取完成的50个链接重新爬取，再爬取当前20个

请作者修复

![image](https://github.com/user-attachments/assets/e630b2e1-bf57-45ed-b25e-23d25a482596)
## 顺便问下
如果网盘链接已经存在，通过API提交的资源，是否会覆盖原资源名称，文件列表等
如果后面可以通过API更新网盘链接的信息是最好的

谢谢！
## 运行环境信息

- ReMan 版本：

[eg: v0.8.15]

- 操作系统：

[eg: Ubuntu 22.04 LTS]

**Comment by Xwudao** [comment]
https://github.com/Xwudao/reman-release/releases/tag/v0.8.16

---

下次说清楚用的哪个api，reman目前和提交相关的api有两个，一个通过文本，一个是通过元信息。

不过依然可以告诉你已在的链接不会重复入库
