### ISSUE TITLE
关于ReMan的数据导出建议

### ISSUE THREAD

**Issue by 9530045** [Xwudao/reman-release#2]
![image](https://github.com/user-attachments/assets/2797fb2c-7f0b-44df-a3ab-48c1d66d45ff)

目前本版中如果要导出数据，作用于其它地方的话，只能选中导出，对于大量或者是全站的数据导出，选中导出显得不够用了。

如果能一键导出全站的数据，对于那些量非常大的，可以分批导出，可以节省非常多的时间。

如果可以的话，希望作者能够添加一个这样的功能，感谢。

**Comment by Xwudao** [comment]
暂不考虑
