### ISSUE TITLE
【FEAT】非网盘通用链接支持

### ISSUE THREAD

**Issue by ymp12345** [Xwudao/reman-release#20]
# 功能请求

## 你期望添加什么样的功能?

希望可以支持非网盘链接搜索，对于资源来说，不一定非得是网盘，可以是如直链，网页等，如果可以支持通用链接，意味着我可以创建任何带链接的页面，收录一些第三方网页的资源，影视站，软件站，等其他的网页链接。

谢谢！

**Comment by Xwudao** [comment]
暂不考虑
