### ISSUE TITLE
【BUG】添加资源失败 get token error

### ISSUE THREAD

**Issue by 1721746938** [Xwudao/reman-release#21]
# BUG 提交

## 用户添加资源失败 后台提示get token error

![872a4b75-b32e-4e8a-afe9-5ea8726ea3d5](https://github.com/user-attachments/assets/5f043f17-d1c3-433a-97c2-c3b80b8bb9f4)

## 运行环境信息

- ReMan 版本：

[eg: v0.8.15]

- 操作系统：

[eg: Ubuntu 22.04 LTS]

## 其它

在此添加关于问题的任何其它信息。

**Comment by Xwudao** [comment]
用本地工具，这个被限制了。没有问我要

> PS: 如果已经私信问过了，以后自己把issue close
