### ISSUE TITLE
【BUG】导入任务时无法自定义资源名称

### ISSUE THREAD

**Issue by ymp12345** [Xwudao/reman-release#22]
# BUG 提交

## 描述该错误
在后台导入任务时，前面写的资源名称，空格，加上夸克网盘的链接
提交后资源名称还是网盘实际的名称，应该如解决

另外，导入网盘链接的API能否增加此功能，一个正确的资源名称非常重要！！

谢谢！

## 复现

![image](https://github.com/user-attachments/assets/b8bcb3b6-90e0-4786-aa10-a72d45a713da)
![image](https://github.com/user-attachments/assets/654da2b7-e99e-4bd1-a255-e3ceefc16e62)

## 运行环境信息

- ReMan 版本：

[eg: v0.8.16]

- 操作系统：

[eg: Ubuntu 22.04 LTS]

**Comment by Xwudao** [comment]
按照要求添加issue，包括标题

**Comment by ymp12345** [comment]
> 按照要求添加issue，包括标题

已修改，不好意思，在办公室，不好弄其他的，麻烦看一下，谢谢！

**Comment by Xwudao** [comment]
![image](https://github.com/user-attachments/assets/acc3447a-17e4-4274-a70c-b902894e8819)


可能之前文档没说清楚，导入时启用“是自己的资源，搜索结果靠前” 才能有效；

API导入时处个版本添加该 功能

**Comment by ymp12345** [comment]
> ![image](https://private-user-images.githubusercontent.com/31327868/392221445-acc3447a-17e4-4274-a70c-b902894e8819.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODU4NDQsIm5iZiI6MTczMzI4NTU0NCwicGF0aCI6Ii8zMTMyNzg2OC8zOTIyMjE0NDUtYWNjMzQ0N2EtMTdlNC00Mjc0LWE3MGMtYjkwMjg5NGU4ODE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA0MTIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMmNmMmU5ODY0MWJhYWRiYzE1ZmYwNGNhOGQwOWVmZDFhN2Q3ZTZhODYwMDg2NTY4NjY4NmQzNGRjZTcwOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pNugZeS5OOALLsj1CVqTVyrZIm0SFIpMUcpXrvgrZsc)
> 
> 可能之前文档没说清楚，导入时启用“是自己的资源，搜索结果靠前” 才能有效；
> 
> API导入下个版本添加该功能

好的谢谢，希望资源不是自己的也可以自定义资源名称，很多资源为了防止屏蔽名字很难搜到
