### ISSUE TITLE
【FEAT】建议增加用户ID免审功能

### ISSUE THREAD

**Issue by ymp12345** [Xwudao/reman-release#23]
# 功能请求

## 你期望添加什么样的功能?

部分长期提交的用户可以判断内容是否合适收录，建议可以按用户ID添加免审功能
审核仅针对部分恶意或者不适合收录的用户。

谢谢！

**Comment by Xwudao** [comment]
https://github.com/Xwudao/reman-release/releases/tag/v0.8.17
