### ISSUE TITLE
【FEAT】不收录重复资源可设置为收录新资源删除旧资源

### ISSUE THREAD

**Issue by ymp12345** [Xwudao/reman-release#24]
# 功能请求

## 你期望添加什么样的功能?

目前确实很多用户一个文件分享多次导致重复
但是还存在老资源失效，需要分享同名新资源的情况
能否识别后，删除同名旧资源，收录新资源

移除相似的影视资源也建议删除旧资源，保留新资源

谢谢！

**Comment by Xwudao** [comment]
暂不考虑
