### ISSUE TITLE
【BUG】抓阿里云盘资，空文件夹也会抓取成功

### ISSUE THREAD

**Issue by 9530045** [Xwudao/reman-release#25]
# BUG 提交

## 描述该错误
最新版本抓取阿里云盘资源的时候，有些是空的文件夹，里面什么都没有，但是会返回成功。

## 复现

这个 BUG 的复现步骤:

就正常抓资源就行了。复现的话，需要一些空文件夹的资源链接
这种错误都集中在，资源只有一个空文件夹，里面什么都没有。
这里我也找到几个空文件夹链接供测试：
https://www.aliyundrive.com/s/bwZ85zn6vbH
https://www.aliyundrive.com/s/FH9aut5HJcN
https://www.aliyundrive.com/s/TBpu4zBKSHh
https://www.aliyundrive.com/s/Thr6Rj6z2d2
https://www.aliyundrive.com/s/u8aZTr9YKBK

## 运行环境信息

- ReMan 版本：

[eg: v0.8.17]

- 操作系统：

[eg: Ubuntu 20.04 LTS]

## 其它

在此添加关于问题的任何其它信息。

**Comment by Xwudao** [comment]
有目录，不会看做空文件夹 

![image](https://github.com/user-attachments/assets/d31b5f4a-31a7-4918-867e-bd1e9c4e4a9b)
