### ISSUE TITLE
【BUG】”资源名称黑名单“不生效

### ISSUE THREAD

**Issue by 9530045** [Xwudao/reman-release#26]
# BUG 提交

## 描述该错误

在抓阿里云盘资源的时候发现，有些资源的“文件夹名称“是广告来命名的。我就在”资源名称黑名单“添加了”关键词“来拦截，但是发现没有用，匹配的关键词是”Q群“广告如下图：
![$1F)P0RZ`SCAMEQ7EIO@T}E](https://github.com/user-attachments/assets/f64a810c-2642-4b6a-a767-531ed1300a04)

资源名称黑名单，添加了拦截词”Q群“
![M0CUAA3KY1VXQSE7P 5@DZP](https://github.com/user-attachments/assets/c1483184-ae73-42e2-9aa5-b31c29b64cde)

## 复现

这个 BUG 的复现步骤:

这个资源链接：https://www.aliyundrive.com/s/ms93kZFeqY2
可以测试下。

## 运行环境信息

- ReMan 版本：

[eg: v0.8.17]

- 操作系统：

[eg: Ubuntu 20.04 LTS]

**Comment by Xwudao** [comment]
![image](https://github.com/user-attachments/assets/2ce55f6c-e04e-4c0a-8f2a-bccbba3ce4d9)

这个才是资源名

**Comment by Xwudao** [comment]
![image](https://github.com/user-attachments/assets/f6509326-1887-474c-9e8c-29ce56d10f40)


突然想起，你这种应该用上面这个黑名单
