### ISSUE TITLE
【FEAT】建议添加可以实时加载的网盘资源

### ISSUE THREAD

**Issue by ymp12345** [Xwudao/reman-release#27]
# 功能请求

## 你期望添加什么样的功能?
能否参考此开源网站的搜索模式
应该是通过调用第三方网盘资源站搜索结果，来获取数据，这样可以保持数据的更新以及可用性
https://www.aipan.me/search?keyword=%25E6%259D%2583%25E5%258A%259B%25E7%259A%2584%25E6%25B8%25B8%25E6%2588%258F#google_vignette

作者可以参考下
谢谢！

**Comment by Xwudao** [comment]
reman定位 是一个管理搜索自己资源的，不要想：“别的地方有这种功能，我要加到reman”

这种需求从来不会被满足
