### ISSUE TITLE
【FEAT】最新入库列表添加页数，新增每日热门

### ISSUE THREAD

**Issue by 9530045** [Xwudao/reman-release#28]
# 功能请求

## 你期望添加什么样的功能?

1.最新入库列表希望添加一个翻页的功能，以及可以在后台手动设置，一页有多少资源数量。

有比较多之前用过论坛的用户建议，有时候他们也不知道要找些什么资源，就是逛一逛，然后看看有没有喜欢的资源。

目前的话，我只想到这种方式来弥补这个短板，如果作者能有更好的方法那就更好了。

![image](https://github.com/user-attachments/assets/46789bf9-0b29-47b1-83e7-8b65c901573c)

2.热门资源，希望能有一个每日热门资源

因为目前的热门资源板块，都是不手动清楚数据会一直没啥变化，如果有一个可以每天根据浏览量，更新的热门列表，也可以增加用户的存留。

![image](https://github.com/user-attachments/assets/8b485b18-13cb-4c02-8ef1-191142fb341f)

**Comment by 9530045** [comment]
再者还可以增加“每日搜索排名”
![image](https://github.com/user-attachments/assets/75a30f54-44d2-46e7-9ddb-f69a37bbf056)

**Comment by Xwudao** [comment]
暂不考虑。

reman定位从来不是论坛程序，

也不会成为什么功能都有一点，但什么功能都不好用的大杂烩
