### ISSUE TITLE
【FEAT】希望能根据不同的网盘分享用户ID设置搜索权重

### ISSUE THREAD

**Issue by ymp12345** [Xwudao/reman-release#29]
# 功能请求

## 你期望添加什么样的功能?
发现有很多夸克网盘的用户资源是批量生成的，如长期更新的动漫资源，生成一次后再也不会更新，占用搜索结果
希望可以为每个用户设置不同的搜索权重，对一些优质的专业分享资源的网盘ID提供更好的展示结果。
麻烦看下哈，谢谢！

**Comment by Xwudao** [comment]
为每个设置不同的权重 不现实，该版本可以为一批用户设置相同权重 

https://github.com/Xwudao/reman-release/releases/tag/v0.9.1
