### ISSUE TITLE
生成会员功能反馈

### ISSUE THREAD

**Issue by kuufuucom** [Xwudao/reman-release#3]
生成的会员，能否直接和后台商品管理里面的会员相关联，输入卡密以后直接成为商品管理里面的会员等级或者时间
现在两个是分开互相不关联的，输入卡密只是卡密会员。

或者，能否会员可以免积分购买！  例如：月卡会员可以设置7折购买，季卡会员可以6折购买，年卡会员可以5折购买，永久会员可以免费购买。  就是资料里面的积分购买设置是否可以默认不同会员按照后台设定的费用策略折扣进行执行。 
![Snipaste_2024-10-19_11-07-59](https://github.com/user-attachments/assets/161efafe-942d-4491-a001-fc0f5fa368fe)
![Snipaste_2024-10-19_11-07-31](https://github.com/user-attachments/assets/31fdf81f-6a1e-4281-9568-7b01c059259f)

**Comment by Xwudao** [comment]
新增“会员码”

https://github.com/Xwudao/reman-release/releases/tag/v0.8.2
