### ISSUE TITLE
Adsense: 请问Adsense广告代码放置在哪个位置

### ISSUE THREAD

**Issue by yomige** [Xwudao/reman-release#30]
程序版本：v0.9.1

```
<!-- Adsense 公共代码 -->
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-xxxxx"
     crossorigin="anonymous"></script>
<!-- 广告_自适应 -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-xxxx"
     data-ad-slot="123456789"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
```

请问是将上面的者两段代码放置在站点配置->广告联盟->Google Ads->Google Adsense脚本这里吗？

[官方文档](https://docs.hunhepan.com/reman/ads.html)写的是放在后台【站点配置】=>【基本配置】中填写 统计代码 项：

![image](https://github.com/user-attachments/assets/f65cc752-cd1b-4634-ac03-fb3ab6f3b81b)

**Comment by Xwudao** [comment]
都可以，只是新版本单独做了一个选项出来 ，可以将脚本放在`站点配置->广告联盟->Google Ads->Google Adsense脚本`

建议是后者，方便以后可能的功能；

**Comment by yomige** [comment]
请问有广告展示的样例站点吗，我是将代码放置在站点配置->广告联盟->Google Ads->Google Adsense这里：

![image](https://github.com/user-attachments/assets/b9f7dff0-cb3a-431c-86a7-9c8e0b609def)

添加的内容为：

```
<!-- Adsense 公共代码 -->
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-xxxxx"
     crossorigin="anonymous"></script>
<!-- 广告_自适应 -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-xxxx"
     data-ad-slot="123456789"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
```

但是没有展示出广告，示例站点：https://www.ddmit.com/ ，请问广告展示在详情页还是哪个页面？

**Comment by Xwudao** [comment]
展示广告需要google先通过站点审核，然后自动展示广告。

且页面满足google要求才会展示。

**Comment by yomige** [comment]
您好，

确认是通过审核的站点：

![image](https://github.com/user-attachments/assets/66e982c6-0518-40ee-ae35-f0feecbb0b5a)

**Comment by Xwudao** [comment]
这样就可以了。

reman只支持自动广告，页面满足要求后，google自动展示广告，首页，详情页都可以。

**Comment by Xwudao** [comment]
![image](https://github.com/user-attachments/assets/fefeefbb-ca45-45fa-a66a-6467ee9d09a1)
