### ISSUE TITLE
用户自行上传的资源能否绑定到用户自己的名下？

### ISSUE THREAD

**Issue by kuufuucom** [Xwudao/reman-release#4]
后台设置了用户导入资源需要登录
但是登录以后资源是上传了，但是无法区分是哪个用户上传的！
能否把资源绑定到用户自己名下？用户可以自己在用户中心进行查看，或者管理员可以后台查看是哪个用户上传的？
主要是为了想识别哪个资源是哪个用户上传的，如果技术有难度，能否在后台加个字段，区别一下？
![Snipaste_2024-10-19_11-36-19](https://github.com/user-attachments/assets/842ceabe-d40a-4882-a9f3-274344cd7052)

**Comment by Xwudao** [comment]
【导入任务】中添加识别：上传用户
【资源列表】中不考虑

![image](https://github.com/user-attachments/assets/36057c87-bbb6-4525-b571-8e303d549727)
