### ISSUE TITLE
有没有办法解决被抓接口问题

### ISSUE THREAD

**Issue by 9530045** [Xwudao/reman-release#7]
事情起因是某一天，我发现网站附带的在线人数功能，在线人数飙升，一直维持在一千左右，高峰期两千多。
但是实际真实人数不过10人，其余人都是抓接口的。像是百度统计也不能计入统计中，百度统计也是一天几百IP
后来我看了网站的访问日志，发现全是搜索接口的访问，一秒都有数十不同ip进行访问。
![QFD``WTPX{B%OK7 ~HS5V0J](https://github.com/user-attachments/assets/90b0b153-06f6-4f54-be29-2936435dd4c2)
我采取的措施：
1.开启搜索登陆
2.开启登陆才能查看资源链接
3.开启关键接口验证
但是过了差不多十天多，情况依旧，主要是服务器资源被严重消耗，但是却没有收益的事情，作者能解决这种情况吗。

**Comment by Xwudao** [comment]
首先，你截图的网站并不能使用
其次，截图网站跳转后的网站并没有开启你说的几个措施
最后，下个版本将会稍微改造下搜索接口
