### ISSUE TITLE
希望添加个留言反馈的功能

### ISSUE THREAD

**Issue by 9530045** [Xwudao/reman-release#8]
如果能有个留言反馈的功能，不论是对用户还是站长，都是比较友好的。

一方面对于用户，例如有什么建议，或者是在本站没有找到想要的资源，想要联系站长，还要特地找到站长的联系方式，可能就会劝退大部分用户了。

对于站长的话，能够让用户更方便的对网站提出建议，提高用户的积极意愿，也是很不错的。

希望作者能考虑一下这个建议，感谢！

**Comment by Xwudao** [comment]
https://github.com/Xwudao/reman-release/releases/tag/v0.8.7
