### ISSUE TITLE
关于百度网盘抓取失败的问题。

### ISSUE THREAD

**Issue by 9530045** [Xwudao/reman-release#9]
目前只发现百度网盘在抓取的时候会出现这个问题，我的服务器是国内的，那这就很大可能跟百度的反爬虫机制有关，我们服务器在抓取百度网盘资源内容时，过于频繁被封ip，导致抓取出来的内容，不能识别资源名称、用户名称等信息，但是后台会返回抓取成功的提示。如下图
![A6UKN}C7B~@V362}E`P~JNW](https://github.com/user-attachments/assets/006aa967-9d48-45ab-b7ab-97926beba266)
而前台是这样显示的，如下图
![ULF`F{YI126MJXK)2QDDLLQ](https://github.com/user-attachments/assets/486c0eba-5a82-43b5-92a1-c3c386505431)
这样就导致我们抓取的标题只有一个 “ . ”
如果后台开启“不收录重复资源”
就会抓取失败，因为抓取的标题都是一个“.”
之前也有过这样的问题，但是换了服务器ip后就解决了，但是最近又发现此类情况，但是我的服务器换ip的次数已经用完了，让我很头疼，我相信应该不是只有我一个人有这种情况的吧？
![5S61JN2V38H 075`A%U2IED](https://github.com/user-attachments/assets/8d3f66e0-47e6-4509-a71c-bc90e239466e)
不知道作者能不能对百度的抓取规则优化一下，或者针对百度网盘的抓取做个代理，每次抓取百度资源的时候用代理ip抓取，最好可以在后台设置，针对某一个网盘开启或者不开启。
这里给一个我常用的代理地址，仅供参考 https://www.xiequ.cn/
![Q 8~F6ES7 Q3TYV85EGN8W9](https://github.com/user-attachments/assets/0a389d2a-391c-4c80-b0dc-ebcb8e6fca25)

**Comment by 9530045** [comment]
如果可以接入代理的话，在被其它网盘封ip的情况下，也能很好的应对。

**Comment by Xwudao** [comment]
https://github.com/Xwudao/reman-release/releases/tag/v0.8.8
